# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e tests

on:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
      - "**/LICENSE"
      - "**/.editorconfig"
      - "**/.eslintignore"
      - "**/.gitignore"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: Run on Cypress e2e tests on Chrome
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and verify Cypress
        run: npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        env:
          CYPRESS_PIZZLY_E2E_AUTH_ID: ${{ secrets.PIZZLY_E2E_AUTH_ID }}
        run: |
          npm run serve &
          npm run tests:chrome
        continue-on-error: false
