# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit tests

on:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
      - "**/LICENSE"
      - "**/.editorconfig"
      - "**/.eslintignore"
      - "**/.gitignore"

jobs:
  unit-tests:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run test
